// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csvzsqwsknusmztdtppb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzdnpzcXdza251c216dGR0cHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTgzMjAsImV4cCI6MjA3MzY5NDMyMH0.MtK8i-yDSzeWdYSUabOe9nId-baNAkv_p7K3lCf6VQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});